language: ruby
rvm:
- 2.3.1
install:
- gem install rake
- bundle install
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: _site
    target_branch: master
    on:
      branch: source


after_success:
  - git clone https://github.com/hibrainnet/hibrainnet.github.io.git
  - cd hibrainnet.github.io
  - shopt -s extglob
  - rm -rf !(.git)
  - cd ..
  - cp -r _site/* hibrainnet.github.io/
  - cd hibrainnet.github.io
  - git add .
  - git commit -m "congraturation"
  - ls -al
  - git branch
  - git push https://$GITHUB_TOKEN@github.com/hibrainnet/hibrainnet.github.io.git master
  - echo {$GITHUB_TOKEN}
  - echo $GITHUB_TOKEN
  - cd ..
