## 사이트 설정
title: 하이브레인넷 부설연구소
email: apps@hibrain.net
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/jekyll-and-hybe"
url: "https://hibrainnet.github.io"

## git 설정
git:
  admins: ## admins에 등록된 사용자만 master에 commit, merge, push를 진행할 수 있음
    - sksong@hibrain.net
    - saltfactory@gmail.com

## github 설정
github_page:
  remote_url: git@bitbucket.org:hibrainnet/jekyll-and-hybe.git
  remote_name: github
  branch: source
  builder: travis
  # remote_name: ?? 이건 왜 필요한건지?

## travis를 이용한 github page 빌드 설정
travis:
  github_token: ${GIHUB_TOKEN}
  target_branch: master
  source_branch: source

## 소셜 서비스 계정
sns:
  twitter: hibrainapps
  github: hibrainnet
  medium: hibrainapps

# twitter_username: hibrainapps
# github_username:  hibrainnet

## 댓글 계정
comments:
  disqus:
    shortname: hibrainappsblog
  facebook:
    admin_id: 100001627773972
    app_id: 147895112528926

## 페이징 설정

pagination:
  type: numbering
  enabled: true
  per_page: 2 # 한 화면에 보여줄 post 갯수
  permalink: '/page/:num'
  limit: 0 # 한번에 보여줄 페이징 숫자
  sort_field: "date"
  sort_reverse: true

# Jekyll 설정
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-compose
  - jekyll-seo-tag

include: ['_pages']

exclude:
  - vendor
  - Gemfile
  - Geffile.lock
  - LICENSE
  - README.md
  - Rakefile

#pre-push hook 변수
#githubURL=소스코드를 push할 URL
#githubBranch=소스코트를 push할 Branch
#remoteName=소스코드를 보낼 remote 이름
githubURL: git@github.com:hibrainnet/jekyll-and-hybe.git
githubBranch: source
remoteName: github
